name: Index updater

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'docs/index.md' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      APIURL: https://api.github.com/repos/oarepo/rfcs
      RAWURL: https://raw.githubusercontent.com/oarepo/rfcs
      GHURL: https://github.com/oarepo/rfcs
      INDEX: docs/index.md
    steps:
      - name: Checkout oarepo/rfcs
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.OAR_BOT }}
      - name: update index
        run: |
          # --- grab all RFCs from docs folder ---
          # index section from start to regexp:
          sed -n '1,/^<!--ts-->/ p' < $INDEX > $INDEX.tmp

          # last commit url in main:
          COMMIT_URL=$(curl -s "$APIURL/git/refs/heads/main" | jq -r '.object.url')
          # tree url of commit:
          TREE_URL=$(curl -s "$COMMIT_URL" | jq -r '.tree.url')
          # docs folder url:
          DOCS_URL=$(curl -s "$TREE_URL" | jq -r '.tree[]|select(.path=="docs").url')
          # RFC files list (by regexp):
          RFC_FILES=$(curl -s "$DOCS_URL" | jq -r '[.tree[]|select(.path|test("^[0-9]{4}-.*\\.md$"))][]|.path')

          for RFC_FILE in $RFC_FILES; do
            echo "RFC_FILE=$RFC_FILE"
            if [[ "$RFC_FILE" =~ ^0*([0-9]{1,4})- ]]; then
              # RFC number:
              ISN="${BASH_REMATCH[1]}"
              # RFC title:
              TITLE=$(curl -s "$RAWURL/main/docs/$RFC_FILE" | sed -n '/^# / { s/^# //; p; q }')
              echo "TITLE=$TITLE"
              # add list item to index:
              echo "* [rfc-$ISN: $TITLE]($GHURL/blob/main/docs/$RFC_FILE)" >> $INDEX.tmp
            else
              echo "Wrong RFC filename"
            fi
          done
          # index section from regexp to eof:
          sed -n '/^<!--te-->/,$ p' < $INDEX >> $INDEX.tmp
          mv $INDEX.tmp $INDEX
          sleep 14
      - name: Commit back
        run: |
          git config --global user.name oarepo-bot
          git config --global user.email noreply@cesnet.cz
          git add $INDEX
          git commit -m "$INDEX update" -m "[skip ci]" && git push
          echo "Done."
