# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Test workflow

on:
  workflow_dispatch:
    inputs:
      title:
        description: Title
        required: false
        default: default_title

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TITLE: ${{ github.event.inputs.title }}
    steps:
      - name: Checkout oarepo/rfcs
        uses: actions/checkout@v2
      - name: with input ${{ github.event.inputs.title }}
        run: |
          echo "Test of input, title:${{ github.event.inputs.title }}"
          echo "${{ github.event.inputs.title }}/$TITLE" >> test.log
          date '+%y%m%d-%H%M%S' >> test.log
      - name: Commit back
        run: |
          echo "Start [$TITLE]"
          git config --global user.name oarepo-bot
          git config --global user.email noreply@cesnet.cz
          cat test.log
          #git checkout -b "$TITLE"
          echo "Done."
